create schema api;

create table api.todos (
  id int primary key generated by default as identity,
  isComplete boolean not null default false,
  title text not null,
  description text not null
);

insert into api.todos (title, description) values
  ('finish tutorial 0','desc001'), ('pat self on back','desc002');

create role web_anon nologin;

grant usage on schema api to web_anon;
grant select on api.todos to web_anon;


create role authenticator noinherit login password '123456';
grant web_anon to authenticator;